Repository JECT-Study/Momentia-FE, pull requests merged in 2024-12, with the labels that each got.

#6 PR 탬플릿 생성
  .github/pull_request_template
Labels: docs

#9 [TASK-44, 45] style: 공용 Input, Button 구현
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/providers/MSWProvider.tsx
  src/app/providers/ReactQueryProvider.tsx
  src/components/Button/CategoryButton.tsx
  src/components/Button/FollowButton.tsx
  src/components/Button/SquareButtonL.tsx
  src/components/Footer/index.tsx
  src/components/Icon/Icon.tsx
  src/components/Icon/icons/Close.tsx
  src/components/Icon/icons/Menu.tsx
  src/components/Icon/iconsNames.ts
  src/components/Input/EmailInput.tsx
  src/components/Input/NicknameInput.tsx
  src/components/Input/PasswordInput.tsx
  src/components/Layout/AppShell.tsx
  src/components/Navbar/index.tsx
  src/mocks/handlers.ts
  src/styles/globals.css
  src/types/IconProps.ts
  src/types/buttons/BaseButtonProps.ts
  src/types/buttons/CategoryButtonProps.ts
  src/types/buttons/FollowButtonProps.ts
  src/types/buttons/SquareButtonLProps.ts
  src/types/index.ts
  tailwind.config.ts
Labels: chore, refactor, feat, style, Priority: Critical

#10 [TASK-46, 47] style: Pagination, FilterDropdown 구현
  src/components/Button/CategoryButton.tsx
  src/components/Button/FollowButton.tsx
  src/components/Button/SquareButtonL.tsx
  src/components/FilterDropdown/index.tsx
  src/components/Icon/Icon.tsx
  src/components/Icon/icons/Close.tsx
  src/components/Icon/icons/Menu.tsx
  src/components/Icon/iconsNames.ts
  src/components/Layout/AppShell.tsx
  src/components/Pagination/index.tsx
Labels: refactor, feat, style, Priority: Critical

#12 [TASK-49] style: 디자인 시스템 변경사항 반영 (국문/영문 폰트 설정, 공용 컴포넌트 기능 추가)
  src/app/fonts/Pretendard-Medium.woff
  src/app/fonts/Pretendard-SemiBold.woff
  src/app/fonts/index.ts
  src/app/layout.tsx
  src/components/FilterDropdown/index.tsx
  src/components/Footer/index.tsx
  src/components/Icon/icons/DropDown.tsx
  src/components/Icon/icons/DropUp.tsx
  src/components/Icon/icons/Lock.tsx
  src/components/Icon/icons/Unlock.tsx
  src/components/Icon/iconsNames.ts
  src/components/Input/EmailInput.tsx
  src/components/Navbar/index.tsx
  src/components/Pagination/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: chore, refactor, feat, style, Priority: High

#11 [TASK-30] 로그인/회원가입 페이지 구현
  package.json
  pnpm-lock.yaml
  public/images/google.svg
  public/images/kakako.svg
  src/apis/.gitkeep
  src/apis/user/login.ts
  src/apis/user/signUp.ts
  src/apis/user/socialLogIn.ts
  src/apis/user/validateEmail.ts
  src/apis/user/validateNickname.ts
  src/app/auth/(authWithLayout)/layout.tsx
  src/app/auth/(authWithLayout)/login/page.tsx
  src/app/auth/(authWithLayout)/signup/page.tsx
  src/app/auth/redirect/[provider]/page.tsx
  src/app/layout.tsx
  src/app/providers/KakaoProvider.tsx
  src/components/Button/SocialLoginButton.tsx
  src/components/Input/EmailInput.tsx
  src/components/Input/NicknameInput.tsx
  src/components/Input/PasswordInput.tsx
  src/components/Layout/AppShell.tsx
  src/components/SocialLoginSection.tsx
  src/constants/.gitkeep
  src/constants/API.ts
  src/mocks/handlers.ts
  src/styles/globals.css
  src/types/auth.ts
  src/types/buttons/BaseButtonProps.ts
  src/types/response.ts
Labels: remove, feat, style, setting, Priority: High

#14 [TASK-55] 공통 컴포넌트 - 작품 카드 구현
  public/images/defaultArtworkImage.png
  public/images/rankingLabel.png
  src/components/Card/ArtworkCard.tsx
  src/types/artwork.ts
Labels: feat

#15 [TASK-49] style: Footer UI 깨짐 현상 해결, FollowButton 색상 변경
  src/components/Button/FollowButton.tsx
  src/components/Input/EmailInput.tsx
  src/components/Layout/AppShell.tsx
  src/styles/globals.css
  src/types/artwork.ts
Labels: chore, fix, style, Priority: Critical

#16 [TASK-30] 로그인/회원가입 유효성 검증 로직 개선
  package.json
  pnpm-lock.yaml
  src/apis/auth/validateEmail.ts
  src/apis/auth/validateNickname.ts
  src/app/auth/(authWithLayout)/sign-in/page.tsx
  src/app/auth/(authWithLayout)/sign-up/page.tsx
  src/components/Input/EmailInput.tsx
  src/components/Input/NicknameInput.tsx
  src/components/Input/PasswordInput.tsx
Labels: chore, refactor, Priority: High

#17 [TASK-56] feat: 내가 팔로우한 작가 카드 구현
  pnpm-lock.yaml
  public/images/defaultProfileImage.png
  src/app/artwork/list/page.tsx
  src/components/Button/FollowButton.tsx
  src/components/Card/ArtworkCard.tsx
  src/components/Layout/AppShell.tsx
  src/components/Navbar/index.tsx
  src/hooks/.gitkeep
  src/hooks/useArtworkList.ts
  src/hooks/useFollowedArtists.ts
  src/mocks/artworkHandlers.ts
  src/mocks/browser.ts
  src/mocks/server.ts
Labels: chore, refactor, fix, feat, style, Priority: High

#21 [TASK-57, 58, 59] feat: 작품 검색 및 FilterDropdown 필터 기능 추가
  src/app/artwork/list/page.tsx
  src/components/Card/ArtworkCard.tsx
  src/components/Carousel/DefaultCarousel.tsx
  src/components/FilterDropdown/index.tsx
  src/hooks/useArtworkList.ts
  src/hooks/useFollowedArtists.ts
  src/mocks/artworkHandlers.ts
Labels: chore, refactor, fix, feat, style, Priority: High

#19 [TASK-62] feat: 작가 프로필 카드 구현
  src/apis/follow/deleteFollow.ts
  src/apis/follow/postFollow.ts
  src/apis/index.ts
  src/components/Button/FollowButton.tsx
  src/components/Card/ArtistProfileCard.tsx
  src/components/Carousel/CarouselIndicator.tsx
  src/components/Carousel/ControllableCarousel.tsx
  src/constants/API.ts
  src/hooks/usePrevNextButtons.tsx
  src/types/artist.ts
  src/types/buttons/FollowButtonProps.ts
  tailwind.config.ts
Labels: feat, style
