Repository JECT-Study/Momentia-FE, pull requests merged in 2025-01, with the labels that each got.

#20 [TASK-51] style: 디자인 시스템 Button 수정사항 반영
  src/components/Button/CategoryButton.tsx
  src/components/Button/FollowButton.tsx
  src/components/Button/OvalButton.tsx
  src/components/Button/SquareButtonL.tsx
  src/types/buttons/BaseButtonProps.ts
  src/types/buttons/OvalButtonProps.ts
  src/types/index.ts
Labels: refactor, style, Priority: Critical

#24 [Hotfix] style: 전체 레이아웃 관련 스타일 코드 추가
  src/components/Layout/AppShell.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: chore, style

#22 [TASK-64, TASK-65] 메인 페이지 구현 및 관련 API 로직 추가
  src/apis/monthly/getMonthlyPopularArtists.ts
  src/apis/monthly/getMonthlyPopularArtwork.ts
  src/app/page.tsx
  src/app/providers/MSWProvider.tsx
  src/components/Card/ArtworkCard.tsx
  src/components/Carousel/ControllableCarousel.tsx
  src/components/MainPage/LatestArtworkSection.tsx
  src/components/MainPage/MonthlyBestArtistSection.tsx
  src/components/MainPage/MonthlyPopularArtworkSection.tsx
  src/constants/API.ts
  src/constants/errorMessage.ts
  src/mocks/handlers.ts
Labels: chore, feat, style, Priority: Critical

#26 [TASK-41, TASK-42] feat: 로그인/회원가입 이후 토큰 핸들링 로직 추가 및 일부 동작 수정
  package.json
  src/apis/auth/postRefreshToken.ts
  src/apis/auth/signIn.ts
  src/apis/auth/signUp.ts
  src/apis/auth/socialSignIn.ts
  src/apis/auth/validateNickname.ts
  src/apis/index.ts
  src/app/auth/(authWithLayout)/layout.tsx
  src/components/Navbar/index.tsx
  src/constants/API.ts
  src/types/auth.ts
  src/utils/tokenHandler.ts
Labels: fix, feat, setting

#27 [TASK-30] feat: 로그인/회원가입 관련 UI 동작 수정
  src/apis/auth/signUp.ts
  src/apis/auth/validateEmail.ts
  src/apis/auth/validateNickname.ts
  src/apis/index.ts
  src/app/auth/(authWithLayout)/layout.tsx
  src/app/auth/(authWithLayout)/sign-in/page.tsx
  src/app/auth/(authWithLayout)/sign-up/page.tsx
  src/app/auth/redirect/[provider]/page.tsx
  src/components/Footer/index.tsx
  src/components/Input/EmailInput.tsx
  src/components/Input/NicknameInput.tsx
  src/components/Input/PasswordInput.tsx
  src/constants/errorMessage.ts
  src/constants/routes.ts
Labels: chore, feat

#29 [TASK-56, TASK-66] feat: 팔로우, 언팔로우 기능 구현
  src/apis/artwork/getArtworkList.ts
  src/apis/artwork/getFollowedArtists.ts
  src/apis/auth/signIn.ts
  src/apis/follow/deleteFollow.ts
  src/apis/follow/postFollow.ts
  src/apis/index.ts
  src/apis/monthly/getMonthlyPopularArtwork.ts
  src/app/auth/(authWithLayout)/sign-in/page.tsx
  src/app/auth/(authWithLayout)/sign-up/page.tsx
  src/components/Button/FollowButton.tsx
  src/components/Card/ArtworkCard.tsx
  src/components/Carousel/ControllableCarousel.tsx
  src/components/Navbar/index.tsx
  src/components/Pagination/index.tsx
  src/components/artwork/FollowedArtistsSection.tsx
  src/constants/routes.ts
  src/hooks/clientStateHooks/usePrevNextButtons.ts
  src/hooks/serverStateHooks/useToggleFollow.ts
  src/mocks/artworkHandlers.ts
  src/types/buttons/FollowButtonProps.ts
Labels: refactor, fix, feat, Priority: High

#28 [TASK-65, TASK-69] feat: Navbar 내 알림/사용자 관련 컴포넌트 추가 및 Navbar 내 버튼 동작 수정
  src/components/FilterDropdown/index.tsx
  src/components/Icon/icons/Settings.tsx
  src/components/Icon/iconsNames.ts
  src/components/Navbar/NavbarNoticeDetail/NoticeContent.tsx
  src/components/Navbar/NavbarNoticeDetail/NoticeHeader.tsx
  src/components/Navbar/NavbarNoticeDetail/NoticeUnit.tsx
  src/components/Navbar/NavbarNoticeDetail/index.tsx
  src/components/Navbar/NavbarUserOption.tsx
  src/components/Navbar/index.tsx
  src/hooks/useClickOutside.tsx
  src/utils/tokenHandler.ts
Labels: chore, feat

#30 [TASK-71] fix: build 시, 뜨는 ESLint 및 setting 관련 에러 모두 해결
  .eslintrc.json
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/apis/artwork/getArtworkList.ts
  src/apis/artwork/getFollowedArtists.ts
  src/apis/auth/postRefreshToken.ts
  src/apis/auth/signIn.ts
  src/apis/auth/signUp.ts
  src/apis/auth/socialSignIn.ts
  src/apis/auth/validateEmail.ts
  src/apis/auth/validateNickname.ts
  src/apis/follow/deleteFollow.ts
  src/apis/follow/postFollow.ts
  src/apis/index.ts
  src/apis/monthly/getMonthlyPopularArtists.ts
  src/apis/monthly/getMonthlyPopularArtwork.ts
  src/app/artwork/list/page.tsx
  src/app/auth/(authWithLayout)/layout.tsx
  src/app/auth/(authWithLayout)/sign-in/page.tsx
  src/app/auth/(authWithLayout)/sign-up/page.tsx
  src/app/auth/redirect/[provider]/page.tsx
  src/app/layout.tsx
  src/app/providers/ReactQueryProvider.tsx
  src/components/Button/FollowButton.tsx
  src/components/Card/ArtistProfileCard.tsx
  src/components/Card/ArtworkCard.tsx
  src/components/Carousel/ControllableCarousel.tsx
  src/components/FilterDropdown/index.tsx
  src/components/Footer/index.tsx
  src/components/Icon/Icon.tsx
  src/components/Icon/icons/Close.tsx
  src/components/Icon/icons/Lock.tsx
  src/components/Icon/icons/Unlock.tsx
  src/components/Input/EmailInput.tsx
  src/components/Input/NicknameInput.tsx
  src/components/Layout/AppShell.tsx
  src/components/MainPage/LatestArtworkSection.tsx
  src/components/MainPage/MonthlyBestArtistSection.tsx
  src/components/MainPage/MonthlyPopularArtworkSection.tsx
  src/components/SocialSignInSection.tsx
  src/components/artwork/FollowedArtistsSection.tsx
  src/hooks/serverStateHooks/useToggleFollow.ts
  src/mocks/artworkHandlers.ts
  src/mocks/handlers.ts
  src/types/artist.ts
  src/types/errorResponse.ts
  src/types/iconProps.ts
  tsconfig.json
Labels: fix, setting, Priority: Critical

#32 [TASK-71] fix: pnpm-lock.yaml 파일이 package.json 파일과 일치하지 않아서 생긴 빌드 에러 해결
  pnpm-lock.yaml
Labels: fix, Priority: Critical

#33 [Hotfix] style, settings: pnpm-lock 파일 수정, 작품 카드 사이즈 추가
  pnpm-lock.yaml
  src/app/artwork/list/page.tsx
  src/components/Card/ArtworkCard.tsx
  src/components/artwork/ArtworkShowcase.tsx
Labels: style, setting

#35 [TASK-71] feat: 1차 출시(배포)를 위해 dev 브랜치 코드를 main 브랜치로 merge
  pnpm-lock.yaml
  src/app/artwork/list/page.tsx
  src/components/Card/ArtworkCard.tsx
  src/components/Icon/icons/DropDown.tsx
  src/components/Icon/icons/DropUp.tsx
  src/components/artwork/ArtworkShowcase.tsx
Labels: fix, Priority: Critical

#36 [Hotfix] fix: 배포판 이슈 수정
  src/apis/artwork/getArtworkList.ts
  src/apis/monthly/getMonthlyPopularArtwork.ts
  src/components/Navbar/index.tsx
Labels: chore, style, Priority: Critical

#37 settings: auto-lableing github action 수정
  .github/workflows/auto_labeling.yml
Labels: chore

#39 [FIX] feat: 팔로우한 작가 api reseponse 타입 추가
  src/apis/artwork/getFollowedArtists.ts
Labels: feature

#38 [FIX] refactor: api 로직과 커스텀 훅 분리
  .github/workflows/pr-issue-event-notifications.yml
  src/apis/auth/signIn.ts
  src/apis/auth/signUp.ts
  src/apis/auth/socialSignIn.ts
  src/app/auth/(authWithLayout)/sign-in/page.tsx
  src/app/auth/(authWithLayout)/sign-up/page.tsx
  src/app/auth/redirect/[provider]/page.tsx
  src/hooks/serverStateHooks/useGetSocialSignIn.ts
  src/hooks/serverStateHooks/usePostSignIn.ts
  src/hooks/serverStateHooks/usePostSignUp.ts
Labels: refactor, bug

#40 [TASK-74, TASK-77] fix: 작품 목록 페이지 반응형 시, UI 깨짐 현상 해결 및 <Image /> 태그에 fill, sizes, priority 지정
  .github/workflows/pr-notifications.yml
  .github/workflows/qodana-code-review.yml
  eslint.config.js
  package.json
  public/images/kakao.svg
  src/apis/artwork/getArtworkList.ts
  src/apis/artwork/getFollowedArtists.ts
  src/app/artwork/list/page.tsx
  src/app/auth/(authWithLayout)/layout.tsx
  src/app/layout.tsx
  src/app/providers/TanStackQueryProvider.tsx
  src/components/ArtworkPage/ArtworkFilter.tsx
  src/components/ArtworkPage/ArtworkSearchBar.tsx
  src/components/ArtworkPage/ArtworkShowcase.tsx
  src/components/ArtworkPage/FollowedArtistsSection.tsx
  src/components/Card/ArtistProfileCard.tsx
  src/components/Card/ArtworkCard.tsx
  src/components/FilterDropdown/index.tsx
  src/components/Footer/index.tsx
  src/components/Layout/AppShell.tsx
  src/components/MainPage/LatestArtworkSection.tsx
  src/components/Navbar/NavbarNoticeDetail/index.tsx
  src/components/Navbar/NavbarUserOption.tsx
  src/components/Navbar/index.tsx
  src/components/SocialSignInSection.tsx
  src/components/artwork/FollowedArtistsSection.tsx
  src/hooks/clientStateHooks/useClickOutside.ts
  src/hooks/serverStateHooks/useArtworkList.ts
  src/hooks/serverStateHooks/useFollowedArtists.ts
  src/types/artwork.ts
Labels: chore, rename, refactor, fix, move, setting, Priority: High, bug, feature

#42 [TASK-67] feat: 디자인 시스템 수정 및 추가사항 반영 (색상, 아이콘, Input)
  src/app/auth/(authWithLayout)/sign-in/page.tsx
  src/app/auth/(authWithLayout)/sign-up/page.tsx
  src/components/ArtworkPage/ArtworkFilter.tsx
  src/components/Button/OvalButton.tsx
  src/components/Button/SquareButtonL.tsx
  src/components/FilterDropdown/index.tsx
  src/components/Icon/iconSizes.ts
  src/components/Icon/icons/MoreVertical.tsx
  src/components/Icon/iconsNames.ts
  src/components/Input/BasicInput.tsx
  src/types/buttons/BaseButtonProps.ts
  tailwind.config.ts
Labels: chore, refactor, style, Priority: High, feature

#43 [TASK-72] feat: 모달 컴포넌트 구현
  .github/workflows/pr-issue-event-notifications.yml
  src/app/@modal/page.tsx
  src/app/auth/(authWithLayout)/layout.tsx
  src/app/auth/(authWithLayout)/sign-in/page.tsx
  src/app/auth/(authWithLayout)/sign-up/page.tsx
  src/app/layout.tsx
  src/components/Button/SquareButtonL.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Navbar/index.tsx
  src/stores/modalStore.ts
Labels: chore, style, bug, feature

#41 [FiX] style: 1차 배포 기준 디자인 피드백 반영
  .github/workflows/pr-notifications.yml
  .github/workflows/qodana-code-review.yml
  package.json
  pnpm-lock.yaml
  src/app/artwork/list/page.tsx
  src/components/Button/OvalButton.tsx
  src/components/Carousel/ControllableCarousel.tsx
  src/components/Carousel/DefaultCarousel.tsx
  src/components/Navbar/NavbarNoticeDetail/NoticeUnit.tsx
  src/components/Navbar/NavbarNoticeDetail/index.tsx
  src/components/Navbar/NavbarUserOption.tsx
  src/components/Navbar/index.tsx
  src/hooks/clientStateHooks/useIsCarouselOverflow.ts
Labels: refactor, style, bug, feature

#44 [FIX] chore: 디렉토리 이름 변경 ( @modal -> @Modal )
  src/app/@Modal/page.tsx
Labels: chore

#45 [FIX] fix: React import 에러 해결 및 logo 경로 참조 수정
  package.json
  pnpm-lock.yaml
  src/app/auth/(authWithLayout)/layout.tsx
  src/app/providers/TanStackQueryProvider.tsx
  src/components/Footer/index.tsx
  src/components/Navbar/index.tsx
  tsconfig.json
Labels: fix, setting, Priority: Critical

#46 [TASK-72] refactor: 모달 구현 로직 변경
  src/app/layout.tsx
  src/app/providers/ModalProvider.tsx
  src/components/Layout/AppShell.tsx
  src/stores/modalStore.ts
Labels: refactor

#47 [TASK-92, TASK-93, TASK-94] style: 작품 업로드 페이지 UI 구현
  src/app/artwork/upload/page.tsx
  src/components/ArtworkPage/ArtworkFilter.tsx
  src/components/Button/OvalButton.tsx
  src/components/FilterDropdown/index.tsx
  src/components/Input/BasicInput.tsx
  src/components/Input/EmailInput.tsx
  src/components/Input/NicknameInput.tsx
  src/components/Input/PasswordInput.tsx
  src/components/Input/Textarea.tsx
  src/components/Navbar/index.tsx
  src/constants/artworkFields.ts
  src/constants/routes.ts
  src/styles/globals.css
  src/types/artwork.ts
  src/types/buttons/OvalButtonProps.ts
Labels: chore, refactor, style, feature

#48 [TASK-84, TASK-85] feat, style: 상세 페이지 우측 버튼 그룹 및 관련 모달 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/apis/artwork/deleteArtworkLike.ts
  src/apis/artwork/postArtworkLike.ts
  src/apis/collection/getAllCollectionList.ts
  src/apis/collection/postCollectionAddArtwork.ts
  src/apis/collection/postCreateCollection.ts
  src/components/ArtworkDetailPage/ButtonGroup.tsx
  src/components/Button/SquareButtonL.tsx
  src/components/Input/BasicInput.tsx
  src/components/Modal/CollectionModal/CollectionUnit.tsx
  src/components/Modal/CollectionModal/CreateCollectionUnit.tsx
  src/components/Modal/CollectionModal/index.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/CreateCollectionModal.tsx
  src/components/Modal/ShareModal.tsx
  src/constants/API.ts
  src/constants/errorMessage.ts
  src/constants/routes.ts
  src/hooks/serverStateHooks/useGetCollectionList.ts
  src/hooks/serverStateHooks/usePostCollectionAddArtwork.tsx
  src/hooks/serverStateHooks/usePostCreateCollection.tsx
  src/hooks/serverStateHooks/useToggleLike.ts
  src/styles/scroll.css
  src/types/artwork.ts
  src/types/collection.ts
  src/utils/.gitkeep
  src/utils/copyClipboard.ts
Labels: chore, style, feature

#50 [TASK-87, TASK-89] feat: 작품 상세 본문 영역, 작가 정보 영역 컴포넌트 추가
  src/apis/artwork/deleteArtworkPost.ts
  src/components/ArtworkDetailPage/ArtistInfoSection.tsx
  src/components/ArtworkDetailPage/ArtworkDetailHeader.tsx
  src/components/ArtworkDetailPage/ArtworkDetailInfoSection.tsx
  src/components/Button/FollowButton.tsx
  src/constants/API.ts
  src/constants/errorMessage.ts
  src/hooks/serverStateHooks/useDeleteArtworkPost.ts
  src/types/artwork.ts
  src/types/buttons/FollowButtonProps.ts
  src/utils/timeFormatter.ts
Labels: feature

#49 [TASK-95, TASK-96] feat: BE Server에 API 연동
  src/apis/artwork/getArtworkList.ts
  src/apis/artwork/patchArtwork.ts
  src/apis/artwork/postArtwork.ts
  src/apis/image/postImage.ts
  src/app/artwork/list/page.tsx
  src/app/artwork/upload/page.tsx
  src/app/auth/(authWithLayout)/layout.tsx
  src/components/ArtworkListPage/ArtworkFilter.tsx
  src/components/ArtworkListPage/ArtworkSearchBar.tsx
  src/components/ArtworkListPage/ArtworkShowcase.tsx
  src/components/ArtworkListPage/FollowedArtistsSection.tsx
  src/components/ArtworkUploadPage/ImageUploadSection.tsx
  src/components/MainPage/LatestArtworkSection.tsx
  src/components/Modal/ConfirmModal.tsx
  src/constants/API.ts
  src/hooks/serverStateHooks/useGetArtworkList.ts
  src/hooks/serverStateHooks/useGetFollowedArtists.ts
  src/hooks/serverStateHooks/usePatchArtwork.ts
  src/hooks/serverStateHooks/usePostArtwork.ts
  src/stores/.gitkeep
  src/types/artwork.ts
Labels: chore, refactor, fix, style, bug, feature
