Repository JECT-Study/Momentia-FE, pull requests merged in 2025-02, with the labels that each got.

#52 [TASK-89] feat, fix : 작품 상세 페이지 미반영 부분 추가 반영
  src/app/artwork/detail/page.tsx
  src/components/ArtworkDetailPage/ArtistInfoSection.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/ArtworkCommentUnit/CommentDefault.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/ArtworkCommentUnit/CommentEdit.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/ArtworkWriteCommentSection.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/index.tsx
  src/components/Card/ArtistProfileCard.tsx
  src/components/Card/ArtworkCard.tsx
  src/constants/routes.ts
  src/hooks/serverStateHooks/useGetArtworkComments.ts
  src/hooks/serverStateHooks/useGetArtworkPost.ts
  src/hooks/serverStateHooks/usePostComment.ts
  src/types/artwork.ts
  src/utils/timeFormatter.ts
Labels: chore, bug, feature

#53 [TASK-95, TASK-96] 작품 이미지, 업로드 및 수정 API 연동 완료
  src/apis/artwork/patchArtwork.ts
  src/apis/artwork/postArtwork.ts
  src/apis/image/postImage.ts
  src/apis/index.ts
  src/app/artwork/upload/page.tsx
  src/components/ArtworkDetailPage/ArtworkDetailInfoSection.tsx
  src/components/ArtworkUploadPage/ImageUploadSection.tsx
  src/components/Input/Textarea.tsx
  src/components/Modal/ConfirmModal.tsx
  src/constants/routes.ts
  src/hooks/serverStateHooks/useGetArtworkPost.ts
  src/hooks/serverStateHooks/usePatchArtwork.ts
  src/hooks/serverStateHooks/usePostArtwork.ts
  src/types/artwork.ts
Labels: chore, refactor, fix, feat, style, Priority: Critical, bug, feature

#55 [TASK-100, TASK-101] feat, chore: 프로필 페이지 하단 멀티 탭 부분 구현 ( 작품 / 좋아요한 작품 )
  package.json
  pnpm-lock.yaml
  src/apis/artwork/getArtworkList.ts
  src/apis/user/getLikedArtworkList.ts
  src/apis/user/getProfileArtworkList.ts
  src/apis/user/getProfileInfo.ts
  src/app/artwork/list/page.tsx
  src/app/artwork/upload/page.tsx
  src/app/profile/page.tsx
  src/components/ArtworkDetailPage/ArtistInfoSection.tsx
  src/components/ArtworkDetailPage/ArtworkDetailHeader.tsx
  src/components/ArtworkDetailPage/ArtworkDetailInfoSection.tsx
  src/components/ArtworkListPage/ArtworkFilter.tsx
  src/components/ArtworkListPage/FollowedArtistsSection.tsx
  src/components/Card/ArtistProfileCard.tsx
  src/components/Card/ArtworkCard.tsx
  src/components/Card/UserArtworkCard/CardController.tsx
  src/components/Card/UserArtworkCard/index.tsx
  src/components/Navbar/NavbarUserOption.tsx
  src/components/Navbar/index.tsx
  src/components/ProfilePage/UserArtworkSection/ArtworkTab.tsx
  src/components/ProfilePage/UserArtworkSection/CollectionTab.tsx
  src/components/ProfilePage/UserArtworkSection/ContentTabs.tsx
  src/components/ProfilePage/UserArtworkSection/LikedTab.tsx
  src/components/ProfilePage/UserArtworkSection/index.tsx
  src/constants/API.ts
  src/constants/pagination.ts
  src/constants/routes.ts
  src/constants/sortOptions.ts
  src/hooks/serverStateHooks/useGetArtworkPost.ts
  src/hooks/serverStateHooks/useGetLikedArtworkList.tsx
  src/hooks/serverStateHooks/useGetProfileArtworkList.tsx
  src/hooks/serverStateHooks/useGetProfileInfo.ts
  src/hooks/serverStateHooks/usePatchArtwork.ts
  src/hooks/serverStateHooks/usePostCollectionAddArtwork.tsx
  src/types/artist.ts
  src/types/artwork.ts
  src/types/user.ts
  src/utils/tokenHandler.ts
Labels: chore, bug, feature

#56 [TASK-106] feat: 프로필 페이지 내 컬렉션 영역 구현 (UI, API 연동 모두 완료)
  src/apis/artwork/deleteArtwork.ts
  src/apis/collection/deleteCollection.ts
  src/apis/collection/getProfileCollectionList.ts
  src/apis/collection/patchCollection.ts
  src/app/artwork/list/page.tsx
  src/app/artwork/upload/page.tsx
  src/app/collection/page.tsx
  src/app/profile/page.tsx
  src/components/ArtworkDetailPage/ArtistInfoSection.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/ArtworkCommentUnit/index.tsx
  src/components/ArtworkDetailPage/ArtworkDetailHeader.tsx
  src/components/ArtworkDetailPage/ArtworkDetailInfoSection.tsx
  src/components/ArtworkListPage/ArtworkFilter.tsx
  src/components/Card/ArtistProfileCard.tsx
  src/components/Card/ArtworkAndCollectionCard/CardController.tsx
  src/components/Card/ArtworkAndCollectionCard/index.tsx
  src/components/Card/ArtworkCard.tsx
  src/components/Card/UserArtworkCard/index.tsx
  src/components/Icon/icons/EditPencil.tsx
  src/components/Icon/icons/Lock.tsx
  src/components/Icon/icons/Trash.tsx
  src/components/Icon/icons/Unlock.tsx
  src/components/Icon/iconsNames.ts
  src/components/Modal/CollectionModal/CollectionUnit.tsx
  src/components/Modal/CollectionModal/CreateCollectionUnit.tsx
  src/components/Modal/CreateCollectionModal.tsx
  src/components/ProfilePage/UserArtworkSection/ArtworkTab.tsx
  src/components/ProfilePage/UserArtworkSection/CollectionTab.tsx
  src/components/ProfilePage/UserArtworkSection/LikedTab.tsx
  src/components/SortDropdown/index.tsx
  src/constants/API.ts
  src/constants/errorMessage.ts
  src/constants/pagination.ts
  src/constants/routes.ts
  src/hooks/serverStateHooks/useDeleteArtwork.ts
  src/hooks/serverStateHooks/useDeleteArtworkPost.ts
  src/hooks/serverStateHooks/useDeleteCollection.ts
  src/hooks/serverStateHooks/useGetProfileCollectionList.ts
  src/hooks/serverStateHooks/usePatchArtwork.ts
  src/hooks/serverStateHooks/usePatchCollection.ts
  src/hooks/serverStateHooks/usePostCollection.tsx
  src/hooks/serverStateHooks/usePostCollectionAddArtwork.tsx
  src/types/collection.ts
Labels: chore, refactor, fix, feat, style, Priority: Critical

#59 [TASK-99] feat: 프로필 페이지 상단 작가 정보 조회 영역 추가
  src/apis/follow/getFollowerList.ts
  src/apis/follow/getFollowingList.tsx
  src/apis/image/postImage.ts
  src/apis/user/patchProfileInfo.ts
  src/apis/user/updateProfileInfo.ts
  src/app/auth/(authWithLayout)/sign-in/page.tsx
  src/app/auth/(authWithLayout)/sign-up/page.tsx
  src/app/profile/page.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/ArtworkCommentUnit/CommentEdit.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/ArtworkCommentUnit/index.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/ArtworkWriteCommentSection.tsx
  src/components/Button/OvalButton.tsx
  src/components/Card/ArtworkAndCollectionCard/index.tsx
  src/components/Input/BasicInput.tsx
  src/components/Modal/CreateCollectionModal.tsx
  src/components/Modal/FollowInfoModal/FollowUserUnit.tsx
  src/components/Modal/FollowInfoModal/FollowerList.tsx
  src/components/Modal/FollowInfoModal/FollowingList.tsx
  src/components/Modal/FollowInfoModal/TransitionToggle.tsx
  src/components/Modal/FollowInfoModal/index.tsx
  src/components/ProfilePage/UserArtworkSection/ArtworkTab.tsx
  src/components/ProfilePage/UserArtworkSection/CollectionTab.tsx
  src/components/ProfilePage/UserArtworkSection/ContentTabs.tsx
  src/components/ProfilePage/UserInfoSection/DefaultUserInfo.tsx
  src/components/ProfilePage/UserInfoSection/EditUserInfo.tsx
  src/components/ProfilePage/UserInfoSection/index.tsx
  src/components/SortDropdown/index.tsx
  src/constants/API.ts
  src/constants/errorMessage.ts
  src/hooks/serverStateHooks/useGetFollowerList.ts
  src/hooks/serverStateHooks/useGetFollowingList.tsx
  src/hooks/serverStateHooks/usePatchProfileInfo.ts
  src/styles/shadow.css
  src/types/artist.ts
  src/types/buttons/OvalButtonProps.ts
  src/types/user.ts
Labels: chore, refactor, style, feature

#62 [FIX] fix: 컬렉션 생성 후 즉시 반영되도록 수정 및 중복 이름 alert 추가
  src/apis/collection/postCollection.ts
  src/app/collection/page.tsx
  src/components/CollectionPage/RenameCollectionModal.tsx
  src/components/Modal/ShareModal.tsx
  src/constants/errorMessage.ts
  src/hooks/serverStateHooks/usePostCollection.tsx
Labels: fix, feat, Priority: Critical

#63 [HOTFIX] fix: 2차 데모데이 관련 수정사항 반영
  src/apis/collection/postCollectionAddArtwork.ts
  src/app/icon.ico
  src/app/layout.tsx
  src/components/ArtworkDetailPage/ArtistInfoSection.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/ArtworkCommentUnit/CommentDefault.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/ArtworkCommentUnit/index.tsx
  src/components/ArtworkDetailPage/ArtworkDetailHeader.tsx
  src/components/ArtworkListPage/FollowedArtistsSection.tsx
  src/components/Button/FollowButton.tsx
  src/components/Card/ArtistProfileCard.tsx
  src/components/Input/Textarea.tsx
  src/components/Modal/CollectionModal/CollectionUnit.tsx
  src/components/Modal/CollectionModal/CreateCollectionUnit.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/FollowInfoModal/FollowUserUnit.tsx
  src/components/Navbar/NavbarUserOption.tsx
  src/components/ProfilePage/UserArtworkSection/CollectionTab.tsx
  src/components/ProfilePage/UserArtworkSection/ContentTabs.tsx
  src/components/ProfilePage/UserArtworkSection/LikedTab.tsx
  src/components/ProfilePage/UserArtworkSection/index.tsx
  src/components/ProfilePage/UserInfoSection/DefaultUserInfo.tsx
  src/components/ProfilePage/UserInfoSection/EditUserInfo.tsx
  src/hooks/serverStateHooks/usePostCollectionAddArtwork.tsx
  src/hooks/serverStateHooks/useToggleFollow.ts
  src/types/buttons/FollowButtonProps.ts
  src/types/user.ts
  src/utils/timeFormatter.ts
Labels: chore, style, bug, feature

#64 [DEPLOY] 2차 데모데이 관련 수정사항 배포
  README.md
  src/apis/collection/postCollection.ts
  src/apis/collection/postCollectionAddArtwork.ts
  src/app/collection/page.tsx
  src/app/icon.ico
  src/app/layout.tsx
  src/components/ArtworkDetailPage/ArtistInfoSection.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/ArtworkCommentUnit/CommentDefault.tsx
  src/components/ArtworkDetailPage/ArtworkCommentSection/ArtworkCommentUnit/index.tsx
  src/components/ArtworkDetailPage/ArtworkDetailHeader.tsx
  src/components/ArtworkListPage/FollowedArtistsSection.tsx
  src/components/Button/FollowButton.tsx
  src/components/Card/ArtistProfileCard.tsx
  src/components/CollectionPage/RenameCollectionModal.tsx
  src/components/Input/Textarea.tsx
  src/components/Modal/CollectionModal/CollectionUnit.tsx
  src/components/Modal/CollectionModal/CreateCollectionUnit.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/FollowInfoModal/FollowUserUnit.tsx
  src/components/Modal/ShareModal.tsx
  src/components/Navbar/NavbarUserOption.tsx
  src/components/ProfilePage/UserArtworkSection/CollectionTab.tsx
  src/components/ProfilePage/UserArtworkSection/ContentTabs.tsx
  src/components/ProfilePage/UserArtworkSection/LikedTab.tsx
  src/components/ProfilePage/UserArtworkSection/index.tsx
  src/components/ProfilePage/UserInfoSection/DefaultUserInfo.tsx
  src/components/ProfilePage/UserInfoSection/EditUserInfo.tsx
  src/constants/errorMessage.ts
  src/hooks/serverStateHooks/usePostCollection.tsx
  src/hooks/serverStateHooks/usePostCollectionAddArtwork.tsx
  src/hooks/serverStateHooks/useToggleFollow.ts
  src/types/buttons/FollowButtonProps.ts
  src/types/user.ts
  src/utils/timeFormatter.ts
Labels: chore, style, bug, feature, documentation

#65 [HOTFIX] 2차 데모데이에 대한 추가 수정사항 반영
  src/apis/monthly/getMonthlyPopularArtists.ts
  src/components/Button/FollowButton.tsx
  src/components/Navbar/index.tsx
  src/hooks/serverStateHooks/useToggleFollow.ts
Labels: refactor, bug

#66 [DEPLOY] 2차 데모데이 관련 추가 수정 사항 배포
  src/apis/monthly/getMonthlyPopularArtists.ts
  src/components/Button/FollowButton.tsx
  src/components/Navbar/index.tsx
  src/hooks/serverStateHooks/useToggleFollow.ts
Labels: refactor, bug

#67 [HOTFIX] 로그인/회원가입 레이아웃 내 정렬 추가
  src/app/auth/(authWithLayout)/layout.tsx
Labels: style

#70 [FIX] fix: 비로그인 사용자가 프로필 페이지의 컬렉션 Tab을 이용할 수 있도록 수정
  src/apis/collection/getProfileCollectionList.ts
Labels: fix, Priority: Critical

#72 [FIX] feat: URL에 선택한 작품 카테고리 반영 및 새로고침 시 '내가 팔로우한 작가' 섹션 토글 상태가 유지되는 기능 추가
  src/app/artwork/list/page.tsx
  src/components/ArtworkListPage/ArtworkFilter.tsx
  src/components/ArtworkListPage/FollowedArtistsSection.tsx
Labels: feat, Priority: Low

#74 [REFACTOR] refactor: onMutate를 활용하여 낙관적 업데이트 적용
  src/hooks/serverStateHooks/useToggleFollow.ts
Labels: refactor
